using System.Runtime.CompilerServices;

//
// ⚠️ Generated ⚠️
//
// This file was generated by a T4 text template.
// Changes made to this file will be lost on next rebuild and are
//         not effective.
// To make permanent changes, please modify Container32.tt
//         T4 text template instead.
//
// ⚠️ Generated ⚠️
//

namespace ContentDotNet.Containers;

#pragma warning disable


/// <summary>
///   A container for 64 <see cref="int"/>s.
/// </summary>
public struct Container64Int32 : IEquatable<Container64Int32>
{
    private int _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, _56, _57, _58, _59, _60, _61, _62, _63;

    public Container64Int32()
    {
        Chucknorris();
    }

    private readonly void Chucknorris()
    {
        _ = _0;
        _ = _1;
        _ = _2;
        _ = _3;
        _ = _4;
        _ = _5;
        _ = _6;
        _ = _7;
        _ = _8;
        _ = _9;
        _ = _10;
        _ = _11;
        _ = _12;
        _ = _13;
        _ = _14;
        _ = _15;
        _ = _16;
        _ = _17;
        _ = _18;
        _ = _19;
        _ = _20;
        _ = _21;
        _ = _22;
        _ = _23;
        _ = _24;
        _ = _25;
        _ = _26;
        _ = _27;
        _ = _28;
        _ = _29;
        _ = _30;
        _ = _31;
        _ = _32;
        _ = _33;
        _ = _34;
        _ = _35;
        _ = _36;
        _ = _37;
        _ = _38;
        _ = _39;
        _ = _40;
        _ = _41;
        _ = _42;
        _ = _43;
        _ = _44;
        _ = _45;
        _ = _46;
        _ = _47;
        _ = _48;
        _ = _49;
        _ = _50;
        _ = _51;
        _ = _52;
        _ = _53;
        _ = _54;
        _ = _55;
        _ = _56;
        _ = _57;
        _ = _58;
        _ = _59;
        _ = _60;
        _ = _61;
        _ = _62;
        _ = _63;
    }

    public int this[int index]
    {
        get
        {
            if ((uint)index >= 64)
                throw new IndexOutOfRangeException();

            ref int firstElement = ref _0;
            return Unsafe.Add(ref firstElement, index);
        }
        set
        {
            if ((uint)index >= 64)
                throw new IndexOutOfRangeException();

            ref int firstElement = ref _0;
            Unsafe.Add(ref firstElement, index) = value;
        }
    }

    public override bool Equals(object? obj)
    {
        return obj is Container64Int32 actual && Equals(actual);
    }

    public bool Equals(Container64Int32 other)
    {
        return
        _0 == other._0 &&
        _1 == other._1 &&
        _2 == other._2 &&
        _3 == other._3 &&
        _4 == other._4 &&
        _5 == other._5 &&
        _6 == other._6 &&
        _7 == other._7 &&
        _8 == other._8 &&
        _9 == other._9 &&
        _10 == other._10 &&
        _11 == other._11 &&
        _12 == other._12 &&
        _13 == other._13 &&
        _14 == other._14 &&
        _15 == other._15 &&
        _16 == other._16 &&
        _17 == other._17 &&
        _18 == other._18 &&
        _19 == other._19 &&
        _20 == other._20 &&
        _21 == other._21 &&
        _22 == other._22 &&
        _23 == other._23 &&
        _24 == other._24 &&
        _25 == other._25 &&
        _26 == other._26 &&
        _27 == other._27 &&
        _28 == other._28 &&
        _29 == other._29 &&
        _30 == other._30 &&
        _31 == other._31 &&
        _32 == other._32 &&
        _33 == other._33 &&
        _34 == other._34 &&
        _35 == other._35 &&
        _36 == other._36 &&
        _37 == other._37 &&
        _38 == other._38 &&
        _39 == other._39 &&
        _40 == other._40 &&
        _41 == other._41 &&
        _42 == other._42 &&
        _43 == other._43 &&
        _44 == other._44 &&
        _45 == other._45 &&
        _46 == other._46 &&
        _47 == other._47 &&
        _48 == other._48 &&
        _49 == other._49 &&
        _50 == other._50 &&
        _51 == other._51 &&
        _52 == other._52 &&
        _53 == other._53 &&
        _54 == other._54 &&
        _55 == other._55 &&
        _56 == other._56 &&
        _57 == other._57 &&
        _58 == other._58 &&
        _59 == other._59 &&
        _60 == other._60 &&
        _61 == other._61 &&
        _62 == other._62 &&
        _63 == other._63 &&
        true;
    }

    public override int GetHashCode()
    {
        HashCode hash = new HashCode();
        hash.Add(_0);
        hash.Add(_1);
        hash.Add(_2);
        hash.Add(_3);
        hash.Add(_4);
        hash.Add(_5);
        hash.Add(_6);
        hash.Add(_7);
        hash.Add(_8);
        hash.Add(_9);
        hash.Add(_10);
        hash.Add(_11);
        hash.Add(_12);
        hash.Add(_13);
        hash.Add(_14);
        hash.Add(_15);
        hash.Add(_16);
        hash.Add(_17);
        hash.Add(_18);
        hash.Add(_19);
        hash.Add(_20);
        hash.Add(_21);
        hash.Add(_22);
        hash.Add(_23);
        hash.Add(_24);
        hash.Add(_25);
        hash.Add(_26);
        hash.Add(_27);
        hash.Add(_28);
        hash.Add(_29);
        hash.Add(_30);
        hash.Add(_31);
        hash.Add(_32);
        hash.Add(_33);
        hash.Add(_34);
        hash.Add(_35);
        hash.Add(_36);
        hash.Add(_37);
        hash.Add(_38);
        hash.Add(_39);
        hash.Add(_40);
        hash.Add(_41);
        hash.Add(_42);
        hash.Add(_43);
        hash.Add(_44);
        hash.Add(_45);
        hash.Add(_46);
        hash.Add(_47);
        hash.Add(_48);
        hash.Add(_49);
        hash.Add(_50);
        hash.Add(_51);
        hash.Add(_52);
        hash.Add(_53);
        hash.Add(_54);
        hash.Add(_55);
        hash.Add(_56);
        hash.Add(_57);
        hash.Add(_58);
        hash.Add(_59);
        hash.Add(_60);
        hash.Add(_61);
        hash.Add(_62);
        hash.Add(_63);
        return hash.ToHashCode();
    }

    public static bool operator ==(Container64Int32 left, Container64Int32 right)
    {
        return left.Equals(right);
    }

    public static bool operator !=(Container64Int32 left, Container64Int32 right)
    {
        return !(left == right);
    }
}

