using System.Runtime.CompilerServices;

//
// ⚠️ Generated ⚠️
//
// This file was generated by a T4 text template.
// Changes made to this file will be lost on next rebuild and are
//         not effective.
// To make permanent changes, please modify Container256.tt
//         T4 text template instead.
//
// ⚠️ Generated ⚠️
//

namespace ContentDotNet.Containers;

#pragma warning disable


/// <summary>
///   A container for 256 <see cref="uint"/>s.
/// </summary>
public struct Container256UInt32 : IEquatable<Container256UInt32>
{
    private uint _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, _56, _57, _58, _59, _60, _61, _62, _63, _64, _65, _66, _67, _68, _69, _70, _71, _72, _73, _74, _75, _76, _77, _78, _79, _80, _81, _82, _83, _84, _85, _86, _87, _88, _89, _90, _91, _92, _93, _94, _95, _96, _97, _98, _99, _100, _101, _102, _103, _104, _105, _106, _107, _108, _109, _110, _111, _112, _113, _114, _115, _116, _117, _118, _119, _120, _121, _122, _123, _124, _125, _126, _127, _128, _129, _130, _131, _132, _133, _134, _135, _136, _137, _138, _139, _140, _141, _142, _143, _144, _145, _146, _147, _148, _149, _150, _151, _152, _153, _154, _155, _156, _157, _158, _159, _160, _161, _162, _163, _164, _165, _166, _167, _168, _169, _170, _171, _172, _173, _174, _175, _176, _177, _178, _179, _180, _181, _182, _183, _184, _185, _186, _187, _188, _189, _190, _191, _192, _193, _194, _195, _196, _197, _198, _199, _200, _201, _202, _203, _204, _205, _206, _207, _208, _209, _210, _211, _212, _213, _214, _215, _216, _217, _218, _219, _220, _221, _222, _223, _224, _225, _226, _227, _228, _229, _230, _231, _232, _233, _234, _235, _236, _237, _238, _239, _240, _241, _242, _243, _244, _245, _246, _247, _248, _249, _250, _251, _252, _253, _254, _255;

    public Container256UInt32()
    {
        Chucknorris();
    }

    private readonly void Chucknorris()
    {
        _ = _0;
        _ = _1;
        _ = _2;
        _ = _3;
        _ = _4;
        _ = _5;
        _ = _6;
        _ = _7;
        _ = _8;
        _ = _9;
        _ = _10;
        _ = _11;
        _ = _12;
        _ = _13;
        _ = _14;
        _ = _15;
        _ = _16;
        _ = _17;
        _ = _18;
        _ = _19;
        _ = _20;
        _ = _21;
        _ = _22;
        _ = _23;
        _ = _24;
        _ = _25;
        _ = _26;
        _ = _27;
        _ = _28;
        _ = _29;
        _ = _30;
        _ = _31;
        _ = _32;
        _ = _33;
        _ = _34;
        _ = _35;
        _ = _36;
        _ = _37;
        _ = _38;
        _ = _39;
        _ = _40;
        _ = _41;
        _ = _42;
        _ = _43;
        _ = _44;
        _ = _45;
        _ = _46;
        _ = _47;
        _ = _48;
        _ = _49;
        _ = _50;
        _ = _51;
        _ = _52;
        _ = _53;
        _ = _54;
        _ = _55;
        _ = _56;
        _ = _57;
        _ = _58;
        _ = _59;
        _ = _60;
        _ = _61;
        _ = _62;
        _ = _63;
        _ = _64;
        _ = _65;
        _ = _66;
        _ = _67;
        _ = _68;
        _ = _69;
        _ = _70;
        _ = _71;
        _ = _72;
        _ = _73;
        _ = _74;
        _ = _75;
        _ = _76;
        _ = _77;
        _ = _78;
        _ = _79;
        _ = _80;
        _ = _81;
        _ = _82;
        _ = _83;
        _ = _84;
        _ = _85;
        _ = _86;
        _ = _87;
        _ = _88;
        _ = _89;
        _ = _90;
        _ = _91;
        _ = _92;
        _ = _93;
        _ = _94;
        _ = _95;
        _ = _96;
        _ = _97;
        _ = _98;
        _ = _99;
        _ = _100;
        _ = _101;
        _ = _102;
        _ = _103;
        _ = _104;
        _ = _105;
        _ = _106;
        _ = _107;
        _ = _108;
        _ = _109;
        _ = _110;
        _ = _111;
        _ = _112;
        _ = _113;
        _ = _114;
        _ = _115;
        _ = _116;
        _ = _117;
        _ = _118;
        _ = _119;
        _ = _120;
        _ = _121;
        _ = _122;
        _ = _123;
        _ = _124;
        _ = _125;
        _ = _126;
        _ = _127;
        _ = _128;
        _ = _129;
        _ = _130;
        _ = _131;
        _ = _132;
        _ = _133;
        _ = _134;
        _ = _135;
        _ = _136;
        _ = _137;
        _ = _138;
        _ = _139;
        _ = _140;
        _ = _141;
        _ = _142;
        _ = _143;
        _ = _144;
        _ = _145;
        _ = _146;
        _ = _147;
        _ = _148;
        _ = _149;
        _ = _150;
        _ = _151;
        _ = _152;
        _ = _153;
        _ = _154;
        _ = _155;
        _ = _156;
        _ = _157;
        _ = _158;
        _ = _159;
        _ = _160;
        _ = _161;
        _ = _162;
        _ = _163;
        _ = _164;
        _ = _165;
        _ = _166;
        _ = _167;
        _ = _168;
        _ = _169;
        _ = _170;
        _ = _171;
        _ = _172;
        _ = _173;
        _ = _174;
        _ = _175;
        _ = _176;
        _ = _177;
        _ = _178;
        _ = _179;
        _ = _180;
        _ = _181;
        _ = _182;
        _ = _183;
        _ = _184;
        _ = _185;
        _ = _186;
        _ = _187;
        _ = _188;
        _ = _189;
        _ = _190;
        _ = _191;
        _ = _192;
        _ = _193;
        _ = _194;
        _ = _195;
        _ = _196;
        _ = _197;
        _ = _198;
        _ = _199;
        _ = _200;
        _ = _201;
        _ = _202;
        _ = _203;
        _ = _204;
        _ = _205;
        _ = _206;
        _ = _207;
        _ = _208;
        _ = _209;
        _ = _210;
        _ = _211;
        _ = _212;
        _ = _213;
        _ = _214;
        _ = _215;
        _ = _216;
        _ = _217;
        _ = _218;
        _ = _219;
        _ = _220;
        _ = _221;
        _ = _222;
        _ = _223;
        _ = _224;
        _ = _225;
        _ = _226;
        _ = _227;
        _ = _228;
        _ = _229;
        _ = _230;
        _ = _231;
        _ = _232;
        _ = _233;
        _ = _234;
        _ = _235;
        _ = _236;
        _ = _237;
        _ = _238;
        _ = _239;
        _ = _240;
        _ = _241;
        _ = _242;
        _ = _243;
        _ = _244;
        _ = _245;
        _ = _246;
        _ = _247;
        _ = _248;
        _ = _249;
        _ = _250;
        _ = _251;
        _ = _252;
        _ = _253;
        _ = _254;
        _ = _255;
    }

    public uint this[int index]
    {
        get
        {
            if ((uint)index >= 256)
                throw new IndexOutOfRangeException();

            ref uint firstElement = ref _0;
            return Unsafe.Add(ref firstElement, index);
        }
        set
        {
            if ((uint)index >= 256)
                throw new IndexOutOfRangeException();

            ref uint firstElement = ref _0;
            Unsafe.Add(ref firstElement, index) = value;
        }
    }

    public override bool Equals(object? obj)
    {
        return obj is Container256UInt32 actual && Equals(actual);
    }

    public bool Equals(Container256UInt32 other)
    {
        return
        _0 == other._0 &&
        _1 == other._1 &&
        _2 == other._2 &&
        _3 == other._3 &&
        _4 == other._4 &&
        _5 == other._5 &&
        _6 == other._6 &&
        _7 == other._7 &&
        _8 == other._8 &&
        _9 == other._9 &&
        _10 == other._10 &&
        _11 == other._11 &&
        _12 == other._12 &&
        _13 == other._13 &&
        _14 == other._14 &&
        _15 == other._15 &&
        _16 == other._16 &&
        _17 == other._17 &&
        _18 == other._18 &&
        _19 == other._19 &&
        _20 == other._20 &&
        _21 == other._21 &&
        _22 == other._22 &&
        _23 == other._23 &&
        _24 == other._24 &&
        _25 == other._25 &&
        _26 == other._26 &&
        _27 == other._27 &&
        _28 == other._28 &&
        _29 == other._29 &&
        _30 == other._30 &&
        _31 == other._31 &&
        _32 == other._32 &&
        _33 == other._33 &&
        _34 == other._34 &&
        _35 == other._35 &&
        _36 == other._36 &&
        _37 == other._37 &&
        _38 == other._38 &&
        _39 == other._39 &&
        _40 == other._40 &&
        _41 == other._41 &&
        _42 == other._42 &&
        _43 == other._43 &&
        _44 == other._44 &&
        _45 == other._45 &&
        _46 == other._46 &&
        _47 == other._47 &&
        _48 == other._48 &&
        _49 == other._49 &&
        _50 == other._50 &&
        _51 == other._51 &&
        _52 == other._52 &&
        _53 == other._53 &&
        _54 == other._54 &&
        _55 == other._55 &&
        _56 == other._56 &&
        _57 == other._57 &&
        _58 == other._58 &&
        _59 == other._59 &&
        _60 == other._60 &&
        _61 == other._61 &&
        _62 == other._62 &&
        _63 == other._63 &&
        _64 == other._64 &&
        _65 == other._65 &&
        _66 == other._66 &&
        _67 == other._67 &&
        _68 == other._68 &&
        _69 == other._69 &&
        _70 == other._70 &&
        _71 == other._71 &&
        _72 == other._72 &&
        _73 == other._73 &&
        _74 == other._74 &&
        _75 == other._75 &&
        _76 == other._76 &&
        _77 == other._77 &&
        _78 == other._78 &&
        _79 == other._79 &&
        _80 == other._80 &&
        _81 == other._81 &&
        _82 == other._82 &&
        _83 == other._83 &&
        _84 == other._84 &&
        _85 == other._85 &&
        _86 == other._86 &&
        _87 == other._87 &&
        _88 == other._88 &&
        _89 == other._89 &&
        _90 == other._90 &&
        _91 == other._91 &&
        _92 == other._92 &&
        _93 == other._93 &&
        _94 == other._94 &&
        _95 == other._95 &&
        _96 == other._96 &&
        _97 == other._97 &&
        _98 == other._98 &&
        _99 == other._99 &&
        _100 == other._100 &&
        _101 == other._101 &&
        _102 == other._102 &&
        _103 == other._103 &&
        _104 == other._104 &&
        _105 == other._105 &&
        _106 == other._106 &&
        _107 == other._107 &&
        _108 == other._108 &&
        _109 == other._109 &&
        _110 == other._110 &&
        _111 == other._111 &&
        _112 == other._112 &&
        _113 == other._113 &&
        _114 == other._114 &&
        _115 == other._115 &&
        _116 == other._116 &&
        _117 == other._117 &&
        _118 == other._118 &&
        _119 == other._119 &&
        _120 == other._120 &&
        _121 == other._121 &&
        _122 == other._122 &&
        _123 == other._123 &&
        _124 == other._124 &&
        _125 == other._125 &&
        _126 == other._126 &&
        _127 == other._127 &&
        _128 == other._128 &&
        _129 == other._129 &&
        _130 == other._130 &&
        _131 == other._131 &&
        _132 == other._132 &&
        _133 == other._133 &&
        _134 == other._134 &&
        _135 == other._135 &&
        _136 == other._136 &&
        _137 == other._137 &&
        _138 == other._138 &&
        _139 == other._139 &&
        _140 == other._140 &&
        _141 == other._141 &&
        _142 == other._142 &&
        _143 == other._143 &&
        _144 == other._144 &&
        _145 == other._145 &&
        _146 == other._146 &&
        _147 == other._147 &&
        _148 == other._148 &&
        _149 == other._149 &&
        _150 == other._150 &&
        _151 == other._151 &&
        _152 == other._152 &&
        _153 == other._153 &&
        _154 == other._154 &&
        _155 == other._155 &&
        _156 == other._156 &&
        _157 == other._157 &&
        _158 == other._158 &&
        _159 == other._159 &&
        _160 == other._160 &&
        _161 == other._161 &&
        _162 == other._162 &&
        _163 == other._163 &&
        _164 == other._164 &&
        _165 == other._165 &&
        _166 == other._166 &&
        _167 == other._167 &&
        _168 == other._168 &&
        _169 == other._169 &&
        _170 == other._170 &&
        _171 == other._171 &&
        _172 == other._172 &&
        _173 == other._173 &&
        _174 == other._174 &&
        _175 == other._175 &&
        _176 == other._176 &&
        _177 == other._177 &&
        _178 == other._178 &&
        _179 == other._179 &&
        _180 == other._180 &&
        _181 == other._181 &&
        _182 == other._182 &&
        _183 == other._183 &&
        _184 == other._184 &&
        _185 == other._185 &&
        _186 == other._186 &&
        _187 == other._187 &&
        _188 == other._188 &&
        _189 == other._189 &&
        _190 == other._190 &&
        _191 == other._191 &&
        _192 == other._192 &&
        _193 == other._193 &&
        _194 == other._194 &&
        _195 == other._195 &&
        _196 == other._196 &&
        _197 == other._197 &&
        _198 == other._198 &&
        _199 == other._199 &&
        _200 == other._200 &&
        _201 == other._201 &&
        _202 == other._202 &&
        _203 == other._203 &&
        _204 == other._204 &&
        _205 == other._205 &&
        _206 == other._206 &&
        _207 == other._207 &&
        _208 == other._208 &&
        _209 == other._209 &&
        _210 == other._210 &&
        _211 == other._211 &&
        _212 == other._212 &&
        _213 == other._213 &&
        _214 == other._214 &&
        _215 == other._215 &&
        _216 == other._216 &&
        _217 == other._217 &&
        _218 == other._218 &&
        _219 == other._219 &&
        _220 == other._220 &&
        _221 == other._221 &&
        _222 == other._222 &&
        _223 == other._223 &&
        _224 == other._224 &&
        _225 == other._225 &&
        _226 == other._226 &&
        _227 == other._227 &&
        _228 == other._228 &&
        _229 == other._229 &&
        _230 == other._230 &&
        _231 == other._231 &&
        _232 == other._232 &&
        _233 == other._233 &&
        _234 == other._234 &&
        _235 == other._235 &&
        _236 == other._236 &&
        _237 == other._237 &&
        _238 == other._238 &&
        _239 == other._239 &&
        _240 == other._240 &&
        _241 == other._241 &&
        _242 == other._242 &&
        _243 == other._243 &&
        _244 == other._244 &&
        _245 == other._245 &&
        _246 == other._246 &&
        _247 == other._247 &&
        _248 == other._248 &&
        _249 == other._249 &&
        _250 == other._250 &&
        _251 == other._251 &&
        _252 == other._252 &&
        _253 == other._253 &&
        _254 == other._254 &&
        _255 == other._255 &&
        true;
    }

    public override int GetHashCode()
    {
        HashCode hash = new HashCode();
        hash.Add(_0);
        hash.Add(_1);
        hash.Add(_2);
        hash.Add(_3);
        hash.Add(_4);
        hash.Add(_5);
        hash.Add(_6);
        hash.Add(_7);
        hash.Add(_8);
        hash.Add(_9);
        hash.Add(_10);
        hash.Add(_11);
        hash.Add(_12);
        hash.Add(_13);
        hash.Add(_14);
        hash.Add(_15);
        hash.Add(_16);
        hash.Add(_17);
        hash.Add(_18);
        hash.Add(_19);
        hash.Add(_20);
        hash.Add(_21);
        hash.Add(_22);
        hash.Add(_23);
        hash.Add(_24);
        hash.Add(_25);
        hash.Add(_26);
        hash.Add(_27);
        hash.Add(_28);
        hash.Add(_29);
        hash.Add(_30);
        hash.Add(_31);
        hash.Add(_32);
        hash.Add(_33);
        hash.Add(_34);
        hash.Add(_35);
        hash.Add(_36);
        hash.Add(_37);
        hash.Add(_38);
        hash.Add(_39);
        hash.Add(_40);
        hash.Add(_41);
        hash.Add(_42);
        hash.Add(_43);
        hash.Add(_44);
        hash.Add(_45);
        hash.Add(_46);
        hash.Add(_47);
        hash.Add(_48);
        hash.Add(_49);
        hash.Add(_50);
        hash.Add(_51);
        hash.Add(_52);
        hash.Add(_53);
        hash.Add(_54);
        hash.Add(_55);
        hash.Add(_56);
        hash.Add(_57);
        hash.Add(_58);
        hash.Add(_59);
        hash.Add(_60);
        hash.Add(_61);
        hash.Add(_62);
        hash.Add(_63);
        hash.Add(_64);
        hash.Add(_65);
        hash.Add(_66);
        hash.Add(_67);
        hash.Add(_68);
        hash.Add(_69);
        hash.Add(_70);
        hash.Add(_71);
        hash.Add(_72);
        hash.Add(_73);
        hash.Add(_74);
        hash.Add(_75);
        hash.Add(_76);
        hash.Add(_77);
        hash.Add(_78);
        hash.Add(_79);
        hash.Add(_80);
        hash.Add(_81);
        hash.Add(_82);
        hash.Add(_83);
        hash.Add(_84);
        hash.Add(_85);
        hash.Add(_86);
        hash.Add(_87);
        hash.Add(_88);
        hash.Add(_89);
        hash.Add(_90);
        hash.Add(_91);
        hash.Add(_92);
        hash.Add(_93);
        hash.Add(_94);
        hash.Add(_95);
        hash.Add(_96);
        hash.Add(_97);
        hash.Add(_98);
        hash.Add(_99);
        hash.Add(_100);
        hash.Add(_101);
        hash.Add(_102);
        hash.Add(_103);
        hash.Add(_104);
        hash.Add(_105);
        hash.Add(_106);
        hash.Add(_107);
        hash.Add(_108);
        hash.Add(_109);
        hash.Add(_110);
        hash.Add(_111);
        hash.Add(_112);
        hash.Add(_113);
        hash.Add(_114);
        hash.Add(_115);
        hash.Add(_116);
        hash.Add(_117);
        hash.Add(_118);
        hash.Add(_119);
        hash.Add(_120);
        hash.Add(_121);
        hash.Add(_122);
        hash.Add(_123);
        hash.Add(_124);
        hash.Add(_125);
        hash.Add(_126);
        hash.Add(_127);
        hash.Add(_128);
        hash.Add(_129);
        hash.Add(_130);
        hash.Add(_131);
        hash.Add(_132);
        hash.Add(_133);
        hash.Add(_134);
        hash.Add(_135);
        hash.Add(_136);
        hash.Add(_137);
        hash.Add(_138);
        hash.Add(_139);
        hash.Add(_140);
        hash.Add(_141);
        hash.Add(_142);
        hash.Add(_143);
        hash.Add(_144);
        hash.Add(_145);
        hash.Add(_146);
        hash.Add(_147);
        hash.Add(_148);
        hash.Add(_149);
        hash.Add(_150);
        hash.Add(_151);
        hash.Add(_152);
        hash.Add(_153);
        hash.Add(_154);
        hash.Add(_155);
        hash.Add(_156);
        hash.Add(_157);
        hash.Add(_158);
        hash.Add(_159);
        hash.Add(_160);
        hash.Add(_161);
        hash.Add(_162);
        hash.Add(_163);
        hash.Add(_164);
        hash.Add(_165);
        hash.Add(_166);
        hash.Add(_167);
        hash.Add(_168);
        hash.Add(_169);
        hash.Add(_170);
        hash.Add(_171);
        hash.Add(_172);
        hash.Add(_173);
        hash.Add(_174);
        hash.Add(_175);
        hash.Add(_176);
        hash.Add(_177);
        hash.Add(_178);
        hash.Add(_179);
        hash.Add(_180);
        hash.Add(_181);
        hash.Add(_182);
        hash.Add(_183);
        hash.Add(_184);
        hash.Add(_185);
        hash.Add(_186);
        hash.Add(_187);
        hash.Add(_188);
        hash.Add(_189);
        hash.Add(_190);
        hash.Add(_191);
        hash.Add(_192);
        hash.Add(_193);
        hash.Add(_194);
        hash.Add(_195);
        hash.Add(_196);
        hash.Add(_197);
        hash.Add(_198);
        hash.Add(_199);
        hash.Add(_200);
        hash.Add(_201);
        hash.Add(_202);
        hash.Add(_203);
        hash.Add(_204);
        hash.Add(_205);
        hash.Add(_206);
        hash.Add(_207);
        hash.Add(_208);
        hash.Add(_209);
        hash.Add(_210);
        hash.Add(_211);
        hash.Add(_212);
        hash.Add(_213);
        hash.Add(_214);
        hash.Add(_215);
        hash.Add(_216);
        hash.Add(_217);
        hash.Add(_218);
        hash.Add(_219);
        hash.Add(_220);
        hash.Add(_221);
        hash.Add(_222);
        hash.Add(_223);
        hash.Add(_224);
        hash.Add(_225);
        hash.Add(_226);
        hash.Add(_227);
        hash.Add(_228);
        hash.Add(_229);
        hash.Add(_230);
        hash.Add(_231);
        hash.Add(_232);
        hash.Add(_233);
        hash.Add(_234);
        hash.Add(_235);
        hash.Add(_236);
        hash.Add(_237);
        hash.Add(_238);
        hash.Add(_239);
        hash.Add(_240);
        hash.Add(_241);
        hash.Add(_242);
        hash.Add(_243);
        hash.Add(_244);
        hash.Add(_245);
        hash.Add(_246);
        hash.Add(_247);
        hash.Add(_248);
        hash.Add(_249);
        hash.Add(_250);
        hash.Add(_251);
        hash.Add(_252);
        hash.Add(_253);
        hash.Add(_254);
        hash.Add(_255);
        return hash.ToHashCode();
    }

    public static bool operator ==(Container256UInt32 left, Container256UInt32 right)
    {
        return left.Equals(right);
    }

    public static bool operator !=(Container256UInt32 left, Container256UInt32 right)
    {
        return !(left == right);
    }
}

