namespace ContentDotNet.Video.Codecs.H264.Rbsp
{
    using ContentDotNet.Video.Shared.ItuT.DescriptorAnnotations;

    public record RbspSequenceParameterSetData(
        [property: UDescriptor("8")] uint ProfileIdc,
        [property: UDescriptor("1")] bool ConstraintSet0Flag,
        [property: UDescriptor("1")] bool ConstraintSet1Flag,
        [property: UDescriptor("1")] bool ConstraintSet2Flag,
        [property: UDescriptor("1")] bool ConstraintSet3Flag,
        [property: UDescriptor("1")] bool ConstraintSet4Flag,
        [property: UDescriptor("1")] bool ConstraintSet5Flag,
        [property: UDescriptor("2")] uint ReservedZero2Bits,
        [property: UDescriptor("8")] uint LevelIdc,
        [property: UeDescriptor] uint SeqParameterSetId,
        [property: UeDescriptor] uint ChromaFormatIdc,
        [property: UDescriptor("1")] bool SeparateColourPlaneFlag,
        [property: UeDescriptor] uint BitDepthLumaMinus8,
        [property: UeDescriptor] uint BitDepthChromaMinus8,
        [property: UDescriptor("1")] bool QpprimeYZeroTransformBypassFlag,
        [property: UDescriptor("1")] bool SeqScalingMatrixPresentFlag,
        bool[] SeqScalingListPresentFlag,
        ScalingMatrixData ScalingMatrix,
        [property: UeDescriptor] uint Log2MaxFrameNumMinus4,
        [property: UeDescriptor] uint PicOrderCntType,
        [property: UeDescriptor] uint Log2MaxPicOrderCntLsbMinus4,
        [property: UDescriptor("1")] bool DeltaPicOrderAlwaysZeroFlag,
        [property: SeDescriptor] int OffsetForNonRefPic,
        [property: SeDescriptor] int OffsetForTopToBottomField,
        [property: UeDescriptor] uint NumRefFramesInPicOrderCntCycle,
        int[] OffsetForRefFrame,
        [property: UeDescriptor] uint MaxNumRefFrames,
        [property: UDescriptor("1")] bool GapsInFrameNumValueAllowedFlag,
        [property: UeDescriptor] uint PicWidthInMbsMinus1,
        [property: UeDescriptor] uint PicHeightInMapUnitsMinus1,
        [property: UDescriptor("1")] bool FrameMbsOnlyFlag,
        [property: UDescriptor("1")] bool MbAdaptiveFrameFieldFlag,
        [property: UDescriptor("1")] bool Direct8x8InferenceFlag,
        [property: UDescriptor("1")] bool FrameCroppingFlag,
        [property: UeDescriptor] uint FrameCropLeftOffset,
        [property: UeDescriptor] uint FrameCropRightOffset,
        [property: UeDescriptor] uint FrameCropTopOffset,
        [property: UeDescriptor] uint FrameCropBottomOffset,
        [property: UDescriptor("1")] bool VuiParametersPresentFlag,
        RbspVuiParameters? VuiParameters);
}
